[build]
  publish = "public"

[[redirects]]
  from = "/v1/*"
  to = "https://models.inference.ai.azure.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "https://models.inference.ai.azure.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}